i3wm: update/change -t/-F/-t/-T flags and fix a toggle focus issue in i3-scratchpad script and update the config in i3/config

diff --git a/i3wm/.config/i3/i3-scratchpad b/i3wm/.config/i3/i3-scratchpad
--- a/i3wm/.config/i3/i3-scratchpad
+++ b/i3wm/.config/i3/i3-scratchpad
@@ -39,11 +39,15 @@
 #        it will create tiling window and resize, you can notice the resize
 #        and most programs don't need float in i3/config
 #        2. remove -K flag since it is only one command, 2022-07-15
+# v1.8 - 1. remove -t, always toggle, that's scrachpad, give -t to -F which toggles floating/tiling smartly
+#        2. remove -f, always focus first, give -f flag to -F which float enabled
+#        2. fix issue when new created and opened window in another workspace
+#        (not been to scratchpad yet), toggle to focus fails, 2022-07-17
 
-VERSION="1.7"
+VERSION="1.8"
 
 print_help() {
-	printf 'Usage: %s [[-a <anchor>] [-d <size>] [-p <pos>] [-s <screen>] [-F]] [-m <edge>] [-f] [-k] [-t] [-u [-w][-o <opts>]] [-v] [-V] <command>\n' "$script_name"
+	printf 'Usage: %s [[-a <anchor>] [-d <size>] [-p <pos>] [-s <screen>] [-f]] [-t] [-m <edge>] [-k] [-u [-w][-o <opts>]] [-v] [-V] <command>\n' "$script_name"
 	printf 'Executes a program in a positioned scratchpad, optionally wrapped in a URxvt window.\n'
 	printf 'Caches optional URxvt wrapper script and stores window id at XDG_RUNTIME_DIR based on command,\n'
 	printf 'so executing the same command will re-use the existing window, if it still exists.\n'
@@ -60,16 +64,14 @@ print_help() {
 	printf ' -h            Prints this help page.\n'
 	printf ' -m <edge>     Animates the movement to target position from specified edge.\n'
 	printf '               Valid values are top, left, bottom, right, or short t, l, b, r\n'
-	printf ' -f            Focus first is not foused, only necessary when used with -t.\n'
-	printf ' -F            Float enabled, better to set in i3/config, you will see the floating move when using -F.\n'
+	printf ' -f            Float enabled, better to set in i3/config, you will see the floating move when using only -f.\n'
 	printf ' -k            Keep window layout, restore its size and position when toggle it back.\n'
 	printf ' -K            Kill a window.\n'
 	printf ' -o <opts>     Extra URxvt options to pass.\n'
 	printf ' -p <pos>      Position of terminal on pixels, in X,Y format.\n'
 	printf '               Negative values can be used as well. Default is 0,0\n'
 	printf ' -s <screen>   Screen identifier, as listed in xrandr. Falls back to primary screen.\n'
-	printf ' -t            Toggles the window.\n'
-	printf ' -T            Toggle floating window smartly.\n'
+	printf ' -t            Toggle floating window smartly.\n'
 	printf ' -u            Use URxvt terminal to launch the command - for command line apps.\n'
 	printf ' -v            Verbose, for debugging.\n'
 	printf ' -V            Print version information.\n'
@@ -89,27 +91,23 @@ echoit() {
 }
 
 toggle_floating_smart() {
-	# hard part, parse json of `i3-msg -t get_tree > file.json`, search for `"floating": "user_on"`
+	# hard part, parse json of `i3-msg -t get_tree > /tmp/tree.json | prettier -w /tmp/tree.json && vim /tmp/tree.json`, search for `"floating": "user_on"`
 	# in the same level, get the value of "window", then this window is floating, compare it with the active window id
 	floating_window_ids=$(i3-msg -t get_tree | jq -r --arg sk floating --arg sv user_on --arg pv window '.. | objects | select(contains({($sk): $sv})) | .[$pv]')
 	window_focused_id="$(xdotool getactivewindow)"
-	i3-msg -q -- "[id=\"$window_focused_id\"] floating toggle"
+	# NOTE: do not put the same command part(floating toggle) in is-msg in if-else into one above here,
+	# it has some werid toggle-small-to-bigger resize effect
 	if [[ "$floating_window_ids" == *"$window_focused_id"* ]]; then
-		debug 'The active window' "$window_focused_id" 'was a floting window, now it is a tiling window'
+		debug 'The active window' "$window_focused_id" 'was a floting window, make it a tiling window'
 		# border + no-window-bar for tiling window
-		i3-msg -q -- "[id=\"$window_focused_id\"] border pixel 3"
+		i3-msg -q -- "[id=\"$window_focused_id\"] floating toggle; [id=\"$window_focused_id\"] border pixel 3"
 	else
-		debug 'The active window' "$window_focused_id" 'was a tiling window, now it is a floating window'
-		# no-border + window-bar for floating window
-		# NOTE: Dropdown(dfined in i3/config for Dropdown kitty) has no-border + no-window-bar
-		window_focused_classname="$(xdotool getactivewindow getwindowclassname)"
-		if [ "Dropdown" = "$window_focused_classname" ]; then
-			i3-msg -q -- "[id=\"$window_focused_id\" class=\"(^Dropdown$)\" ] border pixel 0"
-		else
-			i3-msg -q -- "[id=\"$window_focused_id\" class=\"^(?!Dropdown$)\" ] border normal 0"
-		fi
+		debug 'The active window' "$window_focused_id" 'was a tiling window, make it a floating window'
 		# toggle a window manually to set specific 75%x75% size
-		i3-msg -q -- "[id=\"$window_focused_id\"] resize set 75 ppt 75 ppt; [id=\"$window_focused_id\"] move position center"
+		# no-border + window-bar for floating window
+		i3-msg -q -- "[id=\"$window_focused_id\"] floating toggle; [id=\"$window_focused_id\"] resize set 75 ppt 75 ppt; [id=\"$window_focused_id\"] move position center"
+		# NOTE: no -d options for ./script -t for Dropdown, so it won't be a big window size, toggle Dropdown will do as all other windows
+		i3-msg -q -- "[id=\"$window_focused_id\"] border normal 0"
 	fi
 	exit 0
 }
@@ -117,7 +115,7 @@ toggle_floating_smart() {
 main() {
 	# echo "================================" >>/tmp/i3-scratchpad.log
 	local screen_width screen_height offset_x offset_y width height x_pos y_pos \
-		urxvt move wait command urxvt_opts toggle verbose window_focused_id \
+		urxvt move wait command urxvt_opts verbose window_focused_id \
 		window_state wid_file pid_dir animation_frame_delay=0.01
 
 	pid_dir=${XDG_RUNTIME_DIR:-"/tmp"}
@@ -135,20 +133,18 @@ main() {
 parse_aruments() {
 	local script_name dim='\([0-9]\+%\?\)' pos='\(-\?[0-9]\+\)' anchor='cc'
 	script_name="$(basename "$0")"
-	while getopts a:d:hfFkm:o:p:s:tTuvVw arg; do
+	while getopts a:d:hfkm:o:p:s:tuvVw arg; do
 		case $arg in
 		a) anchor="$OPTARG" ;;
 		d) read -r width height < <(sed -n "s/^${dim}x${dim}$/\1 \2/p" <<<"$OPTARG") ;;
 		h) print_help && exit 0 ;;
-		f) focus=true ;;
-		F) float=true ;;
+		f) float=true ;;
 		k) keep=true ;;
 		m) move="$OPTARG" ;;
 		o) urxvt_opts="$OPTARG" ;;
 		p) read -r x_pos y_pos < <(sed -n "s/^${pos},${pos}$/\1 \2/p" <<<"$OPTARG") ;;
 		s) screen="$OPTARG" ;;
-		t) toggle=true ;;
-		T) toggle_floating_smart && exit 0 ;;
+		t) toggle_floating_smart && exit 0 ;;
 		u) urxvt=true ;;
 		v) verbose=true ;;
 		V) printf 'Version %s\n' "$VERSION" && exit 0 ;;
@@ -247,13 +243,14 @@ already_running() {
 				debug 'Last pid not found'
 			fi
 			window_state=$(xprop -id "$window_id" | sed -n 's/^.*window state: \(.*\)$/\1/p')
-			if [ -n "$toggle" ]; then
-				debug 'Toggle mode on, current window state is' "$window_state"
-				if [[ "$window_state" != 'Withdrawn' ]]; then
-					debug 'Moving to scratchpad'
-					toggle_window
-					return 0
-				fi
+			debug 'Toggle mode on, current window state is' "$window_state"
+			# NOTE: if the window is opened/visiable but in another i3 workspace, its window_state is "Withdrawn"
+			# if the window is in scratchpad and hidden, its window_state is "Withdrawn",
+			# both can use `i3-msg -q -- "[id="37748740"] focus"` to focus its window, other situations are all "Normal"
+			if [[ "$window_state" != 'Withdrawn' ]]; then
+				debug 'Moving to scratchpad'
+				toggle_window
+				return 0
 			fi
 			show_window_in_position
 			return 0
@@ -291,132 +288,123 @@ start_and_save_wid_and_pid() {
 	show_window_in_position
 }
 
-keep_window() {
-	i3-msg -q -- "[id=\"$1\"] scratchpad show;"
-	if [ -n "$keep" ]; then
-		# already in scrachpad and -k flag is used
-		window_currnet_info="$(xwininfo -id "$1")"
-		depth_current=$(echo "$window_currnet_info" | awk '/Depth/ {print $2}')
-		x_pos_current=$(echo "$window_currnet_info" | awk '/Absolute upper-left X/ {print $4}')
-		y_pos_current="$(($(echo "$window_currnet_info" | awk '/Absolute upper-left Y/ {print $4}') - depth_current))"
-		width_current=$(echo "$window_currnet_info" | awk '/Width/ {print $2}')
-		height_current="$(($(echo "$window_currnet_info" | awk '/Height/ {print $2}') + depth_current))"
-
-		debug 'Show window in scratchpad and restore the previous window size and position'
-		i3-msg -q -- "[id=\"$1\"] move position $x_pos_current px $y_pos_current px;[id=\"$1\"] resize set $width_current px $height_current px"
-	else
-		i3-msg -q -- "[id=\"$1\"] move position $x_pos px $y_pos px;[id=\"$1\"] resize set $width px $height px"
-	fi
-}
-
 show_window_in_position() {
+	window_focused_id="$(xdotool getactivewindow)"
+	if [ "$window_focused_id" != "$(printf "%d" "$window_id")" ]; then
+		i3-msg -q -- "[id=\"$window_id\"] focus"
+	fi
+
 	if [ -z "$move" ]; then
-		# check if this is a new created window that has not been put into scrachpad
-		# otherwise the value_current will be the controlled my i3 open-new-window function which is not passed by -d
-		# window_non_scratchpad_ids=$(i3-msg -t get_tree | jq -r --arg sk window --arg sv "$window_focused_id" --arg pv window '.. | objects | select(contains({($sk): $sv})) | .[$pv]')
-		# if [[ "$window_non_scratchpad_ids" != *"$window_focused_id"* && -n "$keep" ]]; then
-		window_state=$(xprop -id "$window_id" | sed -n 's/^.*window state: \(.*\)$/\1/p')
-		if [[ "$window_state" == "Withdrawn" ]]; then
-			if [ -n "$float" ]; then
-				if [ -n "$keep" ]; then
-					keep_window "$window_id"
-				else
-					i3-msg -q -- "[id=\"$window_id\"] scratchpad show"
-					debug 'The window' "$window_id" 'is alredy a floting window, resizez it'
-					i3-msg -q -- "[id=\"$window_id\"] move position $x_pos px $y_pos px;[id=\"$window_id\"] resize set $width px $height px"
-					window_focused_classname="$(xdotool getactivewindow getwindowclassname)"
-					if [ "Dropdown" = "$window_focused_classname" ]; then
-						i3-msg -q -- "[id=\"$window_id\" class=\"(^Dropdown$)\" ] border pixel 0"
-					else
-						i3-msg -q -- "[id=\"$window_id\" class=\"^(?!Dropdown$)\" ] border normal 0"
-					fi
-				fi
+		if [ -n "$float" ]; then
+			if [ -n "$keep" ]; then
+				# already in scrachpad and -k flag is used
+				window_currnet_info="$(xwininfo -id "$window_id")"
+				depth_current=$(echo "$window_currnet_info" | awk '/Depth/ {print $2}')
+				x_pos_current=$(echo "$window_currnet_info" | awk '/Absolute upper-left X/ {print $4}')
+				y_pos_current="$(($(echo "$window_currnet_info" | awk '/Absolute upper-left Y/ {print $4}') - depth_current))"
+				width_current=$(echo "$window_currnet_info" | awk '/Width/ {print $2}')
+				height_current="$(($(echo "$window_currnet_info" | awk '/Height/ {print $2}') + depth_current))"
+
+				debug 'Show window in scratchpad and restore the previous window size and position'
+				i3-msg -q -- "[id=\"$window_id\"] move position $x_pos_current px $y_pos_current px;[id=\"$window_id\"] resize set $width_current px $height_current px"
 			else
-				i3-msg -q -- "[id=\"$window_id\"] scratchpad show; [id=\"$window_id\"] floating toggle; [id=\"$window_id\"] border none"
+				debug 'The window' "$window_id" 'is alredy a floting window'
+				window_focused_classname="$(xdotool getactivewindow getwindowclassname)"
+				if [ "Dropdown" = "$window_focused_classname" ]; then
+					i3-msg -q -- "[id=\"$window_id\"] move position $x_pos px $y_pos px;[id=\"$window_id\"] resize set $width px $height px"
+					i3-msg -q -- "[id=\"$window_id\" class=\"(^Dropdown$)\" ] border pixel 0"
+				else
+					i3-msg -q -- "[id=\"$window_id\" class=\"^(?!Dropdown$)\" ] border normal 0"
+				fi
 			fi
-		else # focus it first
-			i3-msg -q -- "[id=\"$window_id\"] focus"
+		else
+			floating_window_ids=$(i3-msg -t get_tree | jq -r --arg sk floating --arg sv user_on --arg pv window '.. | objects | select(contains({($sk): $sv})) | .[$pv]')
+			window_focused_id="$(xdotool getactivewindow)"
+
+			if [[ "$floating_window_ids" == *"$window_focused_id"* ]]; then
+				i3-msg -q -- "[id=\"$window_focused_id\"] floating toggle"
+				debug 'The active window' "$window_focused_id" 'was a floting window, now it is a tiling window'
+				# border + no-window-bar for tiling window
+				i3-msg -q -- "[id=\"$window_focused_id\"] border pixel 3"
+			fi
 		fi
-		return 0
-	fi
-
-	local x x_inc=0 x_end y y_inc=0 y_end
-	x=$x_pos
-	y=$y_pos
-	x_end=$x_pos
-	y_end=$y_pos
-	case "$move" in
-	t)
-		y=$((offset_y - height + 1))
-		y_inc=$(((y_pos - y) / 4))
-		;;
-	b)
-		y=$((offset_y + screen_height - 1))
-		y_inc=$(((y_pos - y) / 4))
-		;;
-	l)
-		x=$((offset_x - width + 1))
-		x_inc=$(((x_pos - x) / 4))
-		;;
-	r)
-		x=$((offset_x + screen_width - 1))
-		x_inc=$(((x_pos - x) / 4))
-		;;
-	esac
-
-	if [ -n "$float_disable" ]; then
-		i3-msg -q -- "[id=\"$window_id\"] move to scratchpad;[id=\"$window_id\"] scratchpad show"
-		i3-msg -q -- "floating toggle"
 	else
-		i3-msg -q -- "[id=\"$window_id\"] move to scratchpad;[id=\"$window_id\"] scratchpad show;[id=\"$window_id\"] move position $x px $y px;[id=\"$window_id\"] resize set $width px $height px"
+		local x x_inc=0 x_end y y_inc=0 y_end
+		x=$x_pos
+		y=$y_pos
+		x_end=$x_pos
+		y_end=$y_pos
+		case "$move" in
+		t)
+			y=$((offset_y - height + 1))
+			y_inc=$(((y_pos - y) / 4))
+			;;
+		b)
+			y=$((offset_y + screen_height - 1))
+			y_inc=$(((y_pos - y) / 4))
+			;;
+		l)
+			x=$((offset_x - width + 1))
+			x_inc=$(((x_pos - x) / 4))
+			;;
+		r)
+			x=$((offset_x + screen_width - 1))
+			x_inc=$(((x_pos - x) / 4))
+			;;
+		esac
+
+		if [ -n "$float_disable" ]; then
+			i3-msg -q -- "[id=\"$window_id\"] move to scratchpad;[id=\"$window_id\"] scratchpad show"
+			i3-msg -q -- "floating toggle"
+		else
+			i3-msg -q -- "[id=\"$window_id\"] move to scratchpad;[id=\"$window_id\"] scratchpad show;[id=\"$window_id\"] move position $x px $y px;[id=\"$window_id\"] resize set $width px $height px"
+		fi
+		debug 'Starting show animation'
+		while [[ ($x_inc -lt 0 && $x -gt $x_end) || ($x_inc -gt 0 && $x -lt $x_end) || ($y_inc -lt 0 && $y -gt $y_end) || ($y_inc -gt 0 && $y -lt $y_end) ]]; do
+			animate
+		done
+		debug 'Animation completed'
+		i3-msg -q -- "[id=\"$window_id\"] move position $x_pos px $y_pos px"
 	fi
-	debug 'Starting show animation'
-	while [[ ($x_inc -lt 0 && $x -gt $x_end) || ($x_inc -gt 0 && $x -lt $x_end) || ($y_inc -lt 0 && $y -gt $y_end) || ($y_inc -gt 0 && $y -lt $y_end) ]]; do
-		animate
-	done
-	debug 'Animation completed'
-	i3-msg -q -- "[id=\"$window_id\"] move position $x_pos px $y_pos px"
 }
 
 toggle_window() {
 	window_focused_id="$(xdotool getactivewindow)"
 	# the printf part is to convert hex to dec
-	if [[ "$window_focused_id" -ne "$(printf "%d" "$window_id")" && -n "$focus" ]]; then
+	if [[ "$window_focused_id" -ne "$(printf "%d" "$window_id")" ]]; then
 		debug 'window_id does not match current window_focused_id and -f is given, will focus the window_id first'
 		show_window_in_position && return 0
+	elif [ -n "$move" ]; then
+		[ -z "$BASH_LOADABLES_PATH" ] && BASH_LOADABLES_PATH=$(pkg-config bash --variable=loadablesdir 2>/dev/null)
+		local x x_inc=0 x_end y y_inc=0 y_end
+		x=$x_pos
+		y=$y_pos
+		x_end=$x_pos
+		y_end=$y_pos
+		case "$move" in
+		t)
+			y_end=$((offset_y - height))
+			y_inc=$(((y_end - y_pos) / 20))
+			;;
+		b)
+			y_end=$((offset_y + screen_height - 1))
+			y_inc=$(((y_end - y_pos) / 20))
+			;;
+		l)
+			x_end=$((offset_x - width))
+			x_inc=$(((x_end - x_pos) / 20))
+			;;
+		r)
+			x_end=$((offset_x + screen_width - 1))
+			x_inc=$(((x_end - x_pos) / 20))
+			;;
+		esac
+		debug 'Starting hide animation'
+		while [[ ($x_inc -gt 0 && $x -lt $x_end) || ($x_inc -lt 0 && $x -gt $x_end) || ($y_inc -gt 0 && $y -lt $y_end) || ($y_inc -lt 0 && $y -gt $y_end) ]]; do
+			animate
+		done
+		debug 'Animation completed'
 	else
-		if [ -n "$move" ]; then
-			[ -z "$BASH_LOADABLES_PATH" ] && BASH_LOADABLES_PATH=$(pkg-config bash --variable=loadablesdir 2>/dev/null)
-			local x x_inc=0 x_end y y_inc=0 y_end
-			x=$x_pos
-			y=$y_pos
-			x_end=$x_pos
-			y_end=$y_pos
-			case "$move" in
-			t)
-				y_end=$((offset_y - height))
-				y_inc=$(((y_end - y_pos) / 20))
-				;;
-			b)
-				y_end=$((offset_y + screen_height - 1))
-				y_inc=$(((y_end - y_pos) / 20))
-				;;
-			l)
-				x_end=$((offset_x - width))
-				x_inc=$(((x_end - x_pos) / 20))
-				;;
-			r)
-				x_end=$((offset_x + screen_width - 1))
-				x_inc=$(((x_end - x_pos) / 20))
-				;;
-			esac
-			debug 'Starting hide animation'
-			while [[ ($x_inc -gt 0 && $x -lt $x_end) || ($x_inc -lt 0 && $x -gt $x_end) || ($y_inc -gt 0 && $y -lt $y_end) || ($y_inc -lt 0 && $y -gt $y_end) ]]; do
-				animate
-			done
-			debug 'Animation completed'
-		fi
-
 		i3-msg -q -- "[id=\"$window_id\"] move to scratchpad;"
 	fi
 }
