bin: remove gitmux/tdrop/upx, update sysz/trans to the latest version

diff --git a/bin/.local/bin/sysz b/bin/.local/bin/sysz
--- a/bin/.local/bin/sysz
+++ b/bin/.local/bin/sysz
@@ -1,27 +1,39 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-set -f # disable globbing
+set -o pipefail
 shopt -s lastpipe
+shopt -s extglob
 
-SYSZ_VERSION=1.2.2
+export SHELL=bash
 
+PROG=$(basename "$0")
+SYSZ_VERSION=1.4.3
 SYSZ_HISTORY=${SYSZ_HISTORY:-${XDG_CACHE_HOME:-~/.cache}/sysz/history}
+declare -a STATES
+
+_sysz_keys() {
+  cat <<EOF
+Keybindings:
+  TAB           Toggle selection.
+  ctrl-v        'cat' the unit in the preview window.
+  ctrl-s        Select states to match. Selection is reset.
+  ctrl-r        Run daemon-reload. Selection is reset.
+  ctrl-p        History previous.
+  ctrl-n        History next.
+  ?             Show keybindings.
+EOF
+}
 
 _sysz_help() {
-  PROG=$(basename "$0")
   cat >&2 <<EOF
 A utility for using systemctl interactively via fzf.
 
 Usage: $PROG [OPTS...] [CMD] [-- ARGS...]
 
-Select multiple units and commands using TAB.
-
 sudo is invoked automatically, if necessary.
 
 If only one unit is chosen, available commands will be presented
-based on the state of the unit (e.g. start is only shows if active).
-
-Use CTRL-v to run \`systemctl cat <unit>\` in the preview window.
+based on the state of the unit (e.g. "start" only shows if unit is "active").
 
 OPTS:
   -u, --user               Only show --user units
@@ -42,20 +54,26 @@ CMD:
   reload                 systemctl reload <unit>
   en, enable             systemctl enable <unit>
   d, dis, disable        systemctl disable <unit>
+  c, cat                 systemctl cat <unit>
 
   If no command is given, one or more can be chosen interactively.
 
 ARGS are passed to the systemctl command for each selected unit.
 
+$(_sysz_keys)
+
 History:
   $PROG is stored in $SYSZ_HISTORY
   This can be changed with the environment variable: SYSZ_HISTORY
 
-  Use CTRL-p and CTRL-n to navigate through history.
+Some units are colored based on state:
+  green       active
+  red         failed
+  yellow      not-found
 
 Examples:
   $PROG -u                      User units
-  $PROG -sys -s active          Active system units
+  $PROG --sys -s active          Active system units
   $PROG --user --state failed   Failed user units
 
 Examples with commands:
@@ -63,15 +81,15 @@ Examples with commands:
   $PROG --sys s                Get the status of system units
   $PROG --user edit            Edit user units
   $PROG s -- -n100             Show status with 100 log lines
-  $PROG -sys -s active stop    Stop an active system unit
+  $PROG --sys -s active stop    Stop an active system unit
   $PROG -u --state failed r    Restart failed user units
 EOF
 
-  exit 1
+  exit 0
 }
 
 _sysz_run() {
-  [[ $VERBOSE = true ]] && echo '>' "$@"
+  [[ $VERBOSE = true ]] && echo '>' "$@" >&2
   eval "$@" || return $?
 }
 
@@ -85,24 +103,18 @@ _sysz_systemctl() {
 }
 
 _sysz_journalctl() {
-  # remove --system from journalctl
-  if [[ $1 = --system ]]; then
-    shift
+  if [[ $1 = --user ]]; then
+    # use --user-unit flag if it's a user unit
+    _sysz_run journalctl --user-unit="$2" "${@:3}"
+  else
     if [[ $EUID -ne 0 ]]; then
-      # only run sudo if we aren't root and it's a system unit
-      _sysz_run sudo journalctl "$@"
-      return
+      # only run sudo if we aren't root
+      _sysz_run sudo journalctl --unit="$2" "${@:3}"
+    else
+      _sysz_run journalctl --unit="$2" "${@:3}"
     fi
   fi
 
-  # remove --user flag from journalctl
-  # --user and --system don't work the same on journalctl
-  # as they do for systemctl
-  if [[ $1 = --user ]]; then
-    shift
-  fi
-
-  _sysz_run journalctl "$@"
 }
 
 _sysz_manager() {
@@ -140,52 +152,50 @@ _fzf_preview() {
   else
     SYSTEMD_COLORS=1 systemctl "$MANAGER" status --no-pager -- "$UNIT"
   fi
+  exit 0
 }
 
 _sysz_show() {
-  local MANAGER
-  MANAGER=$(_sysz_manager "$1")
-  local UNIT
-  UNIT=${1##* }
+  local manager
+  manager=$(_sysz_manager "$1")
+  local unit
+  unit=${1##* }
 
-  _sysz_systemctl "$MANAGER" show "$UNIT" -p "$2" --value
+  _sysz_systemctl "$manager" show "$unit" -p "$2" --value
 }
 
 _sysz_sort() {
-  while IFS= read -r string; do
-    if [[ $string =~ \[user\].*\.service$ ]]; then
-      # user services
-      N=0
-    elif [[ $string =~ \.service$ ]]; then
-      # system services
-      N=1
-    elif [[ $string =~ \[user\].*\.timer$ ]]; then
-      # user timers
-      N=2
-    elif [[ $string =~ \.timer$ ]]; then
-      # system timers
-      N=3
-    elif [[ $string =~ \[user\].*\.socket$ ]]; then
-      # user sockets
-      N=4
-    elif [[ $string =~ \.socket$ ]]; then
-      # system sockets
-      N=5
-    elif [[ $string =~ \[user\] ]]; then
-      # then user units based on file extenions
-      N=6
+  local str
+  local mgr
+  local unit
+  local n
+  while IFS= read -r str; do
+    mgr=${str%% *}
+    unit_colored=${str##* }
+    unit=${unit_colored//$'\e'[\[(]*([0-9;])[@-n]/}
+
+    if [[ $unit =~ \.service$ ]]; then
+      n=0
+      [[ $mgr = "[system]" ]] && n=1
+    elif [[ $unit =~ \.timer$ ]]; then
+      n=2
+      [[ $mgr = "[system]" ]] && n=3
+    elif [[ $unit =~ \.socket$ ]]; then
+      n=4
+      [[ $mgr = "[system]" ]] && n=5
+    elif [[ $mgr = "[user]" ]]; then
+      n=6
     else
       # then the rest based on file extension
-      N=7
+      n=7
     fi
-    TYPE=${string##*.}
-    UNIT=${string##* }
-    UNIT_WITHOUT_DASH=${UNIT//-/}
-    echo "$N$TYPE$UNIT_WITHOUT_DASH $string"
-  done | sort -f | cut -d' ' -f2-
+    type=${unit##*.}
+    unit_undashed=${unit//-/}
+    echo "$n$type$unit_undashed $mgr $unit_colored"
+  done | sort -bifu | cut -d' ' -f2-
 }
 
-_sysz_list_cmd() {
+_sysz_list() {
   local args
   declare -a args
   args=(
@@ -200,16 +210,36 @@ _sysz_list_cmd() {
   (
     systemctl list-units "${args[@]}"
     systemctl list-unit-files "${args[@]}"
-  ) | awk '{print $1}' | sort -u
+  ) | sort -u -t ' ' -k1,1 |
+    while read -r line; do
+      unit=${line%% *}
+      if [[ $line = *" active "* ]]; then
+        printf '\033[0;32m%s\033[0m\n' "$unit" # green
+      elif [[ $line = *" failed "* ]]; then
+        printf '\033[0;31m%s\033[0m\n' "$unit" # red
+      elif [[ $line = *" not-found "* ]]; then
+        printf '\033[1;33m%s\033[0m\n' "$unit" # red
+      else
+        echo "$unit"
+      fi
+    done
 }
 
 _sysz_list_units() {
   for MANAGER in "${MANAGERS[@]}"; do
-    _sysz_list_cmd "--$MANAGER" | sed -e "s/^/[$MANAGER] /"
+    _sysz_list "--$MANAGER" | sed -e "s/^/[$MANAGER] /"
   done | _sysz_sort
 }
 
 # main
+
+# check fzf version
+MIN_FZF=0.27.1
+if [[ "$(printf '%s\n' "$MIN_FZF" "$(fzf --version | cut -d' ' -f1)" | sort -V | head -n1)" != "$MIN_FZF" ]]; then
+  echo "ERROR: fzf >= $MIN_FZF required" >&2
+  echo "https://github.com/junegunn/fzf#upgrading-fzf" >&2
+  exit 1
+fi
 
 # root doesn't have user units
 if [[ $EUID -eq 0 ]]; then
@@ -225,13 +255,17 @@ while [[ -n $1 ]]; do
     MANAGERS=(user)
     shift
     ;;
-  -s | --sys | --system)
+  --sys | --system)
     MANAGERS=(system)
     shift
     ;;
-  --state)
+  -s | --state)
     STATES+=("--state=$2")
     shift
+    shift
+    ;;
+  --state=*)
+    STATES+=("$1")
     shift
     ;;
   -v | --version)
@@ -253,7 +287,7 @@ done
 
 for STATE in "${STATES[@]}"; do
   STATE="${STATE##*=}"
-  if [[ -n $STATE ]] && ! systemctl --state=help | grep -q "^$STATE"; then
+  if [[ -n $STATE ]] && ! systemctl --state=help | grep -q "^${STATE}$"; then
     echo "ERROR: Invalid state: $STATE" >&2
     exit 1
   fi
@@ -266,12 +300,10 @@ while [[ -n $1 ]]; do
   _fzf_preview)
     shift
     _fzf_preview "$@"
-    exit 0
     ;;
   _fzf_cat)
     shift
     _fzf_cat "$@"
-    exit 0
     ;;
   h | help)
     _sysz_help
@@ -321,36 +353,116 @@ done
 mkdir -p "$(dirname "$SYSZ_HISTORY")"
 touch "$SYSZ_HISTORY"
 
-_sysz_list_units |
-  fzf \
-    --exact \
-    --multi \
-    --ansi \
-    --reverse \
-    --no-sort \
-    --history="$SYSZ_HISTORY" \
-    --prompt="Units: " \
-    --bind "ctrl-v:preview('${BASH_SOURCE[0]}' _fzf_cat {})" \
-    --preview="'${BASH_SOURCE[0]}' _fzf_preview {}" \
-    --preview-window=70% |
-  readarray -t PICKS
+function join_by {
+  # https://stackoverflow.com/a/17841619/334632
+  local d=${1-} f=${2-}
+  if shift 2; then
+    printf %s "$f" "${@/#/$d}"
+  fi
+}
 
-if [[ ${#PICKS[@]} -eq 0 ]]; then
-  exit 1
-fi
+_sysz_daemon_reload() {
+  (
+    if [[ $EUID -ne 0 ]]; then
+      echo '[system] daemon-reload'
+    fi
+    echo '[user] daemon-reload'
+  ) |
+    fzf \
+      --multi \
+      --no-info \
+      --prompt="Reload: " |
+    readarray -t RELOADS || exit $?
 
-printf -v PICKS_STR '%s\n' "${PICKS[@]}"
+  for RELOAD in "${RELOADS[@]}"; do
+    case $RELOAD in
+    '[user] daemon-reload')
+      _sysz_systemctl --user daemon-reload >&2
+      ;;
+    '[system] daemon-reload')
+      _sysz_systemctl --system daemon-reload >&2
+      ;;
+    esac
+  done
+}
+
+_sysz_states() {
+  # hide 'ing' because they are transient states
+  # which people probably aren't looking for
+  systemctl --state=help |
+    grep -v ':' |
+    grep -v 'ing' |
+    sort -u |
+    grep -v '^$' |
+    fzf \
+      --multi \
+      --prompt="States: " |
+    readarray -t PICKED_STATES || exit $?
+
+  if [[ ${#PICKED_STATES[@]} -gt 0 ]]; then
+    STATES=()
+  fi
+
+  for STATE in "${PICKED_STATES[@]}"; do
+    STATES+=("--state=$STATE")
+  done
+}
+
+while :; do
+  UNITS=()
+  KEY=
+
+  # prompt units
+  _sysz_list_units |
+    fzf \
+      --multi \
+      --ansi \
+      --expect=ctrl-r,ctrl-s \
+      --history="$SYSZ_HISTORY" \
+      --prompt="Units: " \
+      --header '? for keybindings' \
+      --bind "?:preview(echo '$(_sysz_keys)')" \
+      --bind "ctrl-v:preview('${BASH_SOURCE[0]}' _fzf_cat {})" \
+      --preview="'${BASH_SOURCE[0]}' _fzf_preview {}" \
+      --preview-window=70% |
+    readarray -t PICKS
+
+  KEY=${PICKS[0]}
+  [[ $VERBOSE = true ]] && echo "KEY: $KEY" >&2
+  UNITS=("${PICKS[@]:1}")
+
+  case $KEY in
+  ctrl-r)
+    _sysz_daemon_reload
+    continue
+    ;;
+  ctrl-s)
+    _sysz_states
+    continue
+    ;;
+  esac
+
+  if [[ ${#UNITS[@]} -eq 0 ]]; then
+    exit 1
+  fi
+
+  break
+
+done
+
+[[ $VERBOSE = true ]] && printf 'UNIT: %s\n' "${UNITS[@]}" >&2
 
 declare -a CMDS
 if [[ -n $CMD ]]; then
   CMDS=("$CMD")
 else
 
-  if [[ ${#PICKS[@]} -gt 1 ]]; then
-    PREVIEW="echo '$PICKS_STR'"
+  if [[ ${#UNITS[@]} -gt 1 ]]; then
+    printf -v PREVIEW '%s\n' "${UNITS[@]}"
+    PREVIEW_CMD="echo -n '$PREVIEW'"
     MULTI=true
   else
-    UNIT=${PICKS[0]}
+    UNIT=${UNITS[0]}
 
     if [[ $UNIT = *@.* ]]; then
       read -r -p "$UNIT requires a parameter: " PARAM ||
@@ -360,66 +472,77 @@ else
         fi
 
       UNIT=${UNIT/\@/\@${PARAM}}
-      PICKS[0]=$UNIT
+      UNITS[0]=$UNIT
     fi
 
     ACTIVE_STATE=$(_sysz_show "$UNIT" ActiveState)
+    LOAD_STATE=$(_sysz_show "$UNIT" LoadState)
     UNIT_FILE_STATE=$(_sysz_show "$UNIT" UnitFileState)
     CAN_RELOAD=$(_sysz_show "$UNIT" CanReload)
-    PREVIEW="'${BASH_SOURCE[0]}' _fzf_preview '$UNIT'"
+    PREVIEW_CMD="'${BASH_SOURCE[0]}' _fzf_preview '$UNIT'"
   fi
 
+  # prompt commands
   fzf \
     --multi \
     --ansi \
     --no-info \
-    --reverse \
-    --no-sort \
-    --preview="$PREVIEW" \
     --prompt="Commands: " \
-    < <(
+    --preview="$PREVIEW_CMD" \
+    --preview-window=80% < <(
       # status
       echo status "${ARGS[*]}"
       # restart
       [[ $MULTI = true || $ACTIVE_STATE = active ]] &&
-        printf '\033[0;31m%s\033[0m %s\n' restart "${ARGS[*]}"
+        printf '\033[0;31m%s\033[0m %s\n' restart "${ARGS[*]}" # red
       # start
       [[ $MULTI = true || $ACTIVE_STATE != active ]] &&
-        printf '\033[0;32m%s\033[0m %s\n' start "${ARGS[*]}"
+        printf '\033[0;32m%s\033[0m %s\n' start "${ARGS[*]}" # green
       # stop
       [[ $MULTI = true || $ACTIVE_STATE = active ]] &&
-        printf '\033[0;31m%s\033[0m %s\n' stop "${ARGS[*]}"
+        printf '\033[0;31m%s\033[0m %s\n' stop "${ARGS[*]}" # red
       # enable
       [[ $MULTI = true || $UNIT_FILE_STATE != enabled ]] &&
         {
-          printf '\033[0;32m%s\033[0m %s\n' "enable" "${ARGS[*]}"
+          printf '\033[0;32m%s\033[0m %s\n' "enable" "${ARGS[*]}" # green
           printf '\033[0;32m%s\033[0m %s\n' "enable" "--now ${ARGS[*]}"
         }
       # disable
       [[ $MULTI = true || $UNIT_FILE_STATE = enabled ]] &&
         {
-          printf '\033[0;31m%s\033[0m %s\n' disable "${ARGS[*]}"
+          printf '\033[0;31m%s\033[0m %s\n' disable "${ARGS[*]}" # red
           printf '\033[0;31m%s\033[0m %s\n' disable "--now ${ARGS[*]}"
         }
-      # reload
-      [[ $MULTI = true || $CAN_RELOAD = yes ]] &&
-        printf '\033[0;37m%s\033[0m %s\n' reload "${ARGS[*]}"
-      # edit
-      echo show "${ARGS[*]}"
-      # edit
-      echo edit "${ARGS[*]}"
+
       # journal
       echo journal "${ARGS[*]}"
       echo follow "${ARGS[*]}"
+
+      # reload
+      [[ $MULTI = true || $CAN_RELOAD = yes ]] &&
+        printf '\033[0;37m%s\033[0m %s\n' reload "${ARGS[*]}" # green
+
+      # mask
+      [[ $MULTI = true || ($UNIT_FILE_STATE != masked && $LOAD_STATE != masked) ]] &&
+        printf '\033[0;31m%s\033[0m %s\n' mask "${ARGS[*]}" # red
+      [[ $MULTI = true || $UNIT_FILE_STATE = masked || $LOAD_STATE = masked ]] &&
+        printf '\033[0;32m%s\033[0m %s\n' unmask "${ARGS[*]}" # green
+
+      # cat
+      echo cat "${ARGS[*]}"
+      # edit
+      echo edit "${ARGS[*]}"
+      # show
+      echo show "${ARGS[*]}"
     ) |
-    readarray -t CMDS
+    readarray -t CMDS || exit $?
 fi
 
 if [[ ${#CMDS[@]} -eq 0 ]]; then
   exit 1
 fi
 
-for PICK in "${PICKS[@]}"; do
+for PICK in "${UNITS[@]}"; do
 
   MANAGER=$(_sysz_manager "$PICK")
   UNIT=${PICK##* }
@@ -427,24 +550,26 @@ for PICK in "${PICKS[@]}"; do
   for CMD in "${CMDS[@]}"; do
     case ${CMD%% *} in
     journal)
-      _sysz_journalctl "$MANAGER" -xe "--unit=$UNIT" "${ARGS[@]}"
+      _sysz_journalctl "$MANAGER" "$UNIT" -xe "${ARGS[@]}"
       ;;
     follow)
-      _sysz_journalctl "$MANAGER" -xef "--unit=$UNIT" "${ARGS[@]}"
+      _sysz_journalctl "$MANAGER" "$UNIT" -xef "${ARGS[@]}"
       ;;
     status)
       # shellcheck disable=2086
       SYSTEMD_COLORS=1 systemctl "$MANAGER" $CMD --no-pager "${ARGS[@]}" -- "$UNIT"
       ;;
+    cat | show)
+      _sysz_systemctl "$MANAGER" "$CMD" "${ARGS[@]}" -- "$UNIT" || exit $?
+      ;;
     *)
       # shellcheck disable=2086
-      _sysz_systemctl $MANAGER $CMD "${ARGS[@]}" -- "$UNIT" || CODE=$?
+      _sysz_systemctl "$MANAGER" $CMD "${ARGS[@]}" -- "$UNIT" || CODE=$?
       SYSTEMD_COLORS=1 systemctl "$MANAGER" status --no-pager -- "$UNIT"
-      if [[ ${#PICKS[@]} -eq 1 ]]; then
+      if [[ ${#UNITS[@]} -eq 1 ]]; then
         exit $CODE
       fi
       ;;
     esac
   done
-
 done
