bin: tmux command to check SHELL

diff --git a/local/.local/bin/t b/local/.local/bin/t
--- a/local/.local/bin/t
+++ b/local/.local/bin/t
@@ -1,25 +1,23 @@
 #!/bin/bash
 
-t () { # set $SHELL fish it if is bash, and attach tmux session if exists
-        if not hash tmux 2>/dev/null; then
-                echo tmux is not installed, please instsall it!
-        fi
+t () { # set $SHELL fish if it is not, attach tmux session if exists
+	if ! hash tmux 2>/dev/null; then
+		echo tmux is not installed, please install it!
+		return 1
+	fi
 
-        if [ $(basename $SHELL) == "bash" ]; then
-                if [ -f ~/anaconda3/bin/fish ]; then
-                        export SHELL=~/anaconda3/bin/fish
-                elif hash fish 2>/dev/null; then
-                        export SHELL=$(which fish)
-                fi
-        fi
+	if [ $(basename $SHELL) != "fish" ]; then
+		if [ -f ~/anaconda3/bin/fish ]; then
+			export SHELL=~/anaconda3/bin/fish
+		elif hash fish 2>/dev/null; then
+			export SHELL=$(which fish)
+		else
+			echo "No fish is installed, using old $SHELL as SHELL!"
+		fi
+	fi
 
-        if [ "$TERM" != "screen-256color" ] && [ "$TMUX" != "" ]; then
-                tmux attach
-        elif [ "$TERM" != "screen-256color" ] && [ "$TMUX" = "" ]; then
-                tmux
-        else
-                echo Already inside a tmux session!
-        fi
+	# attach a session if it exists, it failed, tmux a new one, if failed, echo message
+	tmux attach 2>/dev/null || tmux 2>/dev/null || echo "Already inside a tmux session!"
 }
 
 t
